//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature1
    {
        public int FeatureID { get; set; }
        public string FeatureBaslik { get; set; }
        public string FeatureAltBaslik { get; set; }
        public string FeatureAciklama { get; set; }
    }
}
