//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioProjesi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyPortfolioDbEntities : DbContext
    {
        public MyPortfolioDbEntities()
            : base("name=MyPortfolioDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Testimonial> Testimonials { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Adress> Adresses { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Feature1> Feature1 { get; set; }
        public virtual DbSet<Award> Awards { get; set; }
        public virtual DbSet<QuickContact> QuickContacts { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
    }
}
